POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "naveen",
  "name": "Adam Richard",
  "password": "996633",
  "gender": "male",
  "location": "Detroit"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "naveen",
    "password": "996633"
}
###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}